name: mi_app_peluqueria
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- INICIO DE LA CORRECCIÓN ---
  # 'flutter_localizations' debe ir aquí, dentro de 'dependencies'
  flutter_localizations:
    sdk: flutter
  # --- FIN DE LA CORRECCIÓN ---

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  image_picker: ^1.2.0
  path_provider: ^2.1.5
  table_calendar: ^3.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

# La configuración del ícono está bien aquí
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagenes/logo.png"
  min_sdk_android: 21

# La configuración de flutter está bien aquí
flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/